### ISSUE TITLE
Remove lodash?

### ISSUE THREAD

**Issue by jimmywarting** [gr2m/selsa#13]
You don't use lodash for much anything else then defaultDeeps
[object destructuring](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) & [default arguments](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Default_parameters) can simplify the process and you won't have to include the hole lodash library only to use < 1% of the features it provide

```js
function foo(opts = {}) {
  let {port = 8000} = opts
  return port
}

console.log(foo({port: 80})) // 80
console.log(foo()) // 8000
```

**Comment by gr2m** [comment]
How about we replace `lodash` with [`lodash.defaultsDeep`](https://www.npmjs.com/package/lodash.defaultsdeep)? Could you send a PR for that?
